package constants

const (
	PG_UNIQUE_VIOLATION_ERR_CODE             = "23505"
	PG_CHECK_VIOLATION_ERR_CODE              = "23514"
	PG_NOT_NULL_VIOLATION_ERR_CODE           = "23502"
	PG_FOREIGN_KEY_VIOLATION_ERR_CODE        = "23503"
	PG_STRING_DATA_RIGHT_TRUNCATION_ERR_CODE = "22001"
)
